#!/usr/bin/env python

from os import walk
import argparse, os, shutil, re, time
import exifread, subprocess

parser = argparse.ArgumentParser(description='Organise media files into folders by date')
requiredNamed = parser.add_argument_group('required named arguments')
requiredNamed.add_argument("-d", "--dir",  help="The directory", required=True)
args = parser.parse_args()

if not os.path.isdir(args.dir):
    print("%s is not a directory" % args.dir)
    exit()

def move(folder, yearmonth, filename, i, n):
    datefolder = os.path.join(folder, yearmonth)

    if not os.path.exists(datefolder):
        os.makedirs(datefolder)

    # Move
    shutil.move(os.path.join(folder, filename), os.path.join(datefolder, filename))
    
    # Info
    print("%d of %d - %d%% completed: %s -> %s" % (i, n, i*100.0/n, filename, yearmonth))


# CONSTANTS
prefixes = ['VID_', 'VID-', 'IMG_', 'IMG-', 'PHOTO_', 'PANO_', 'AUD-', 'snap_']
regexps = ['(\d{4})-(\d{2})-(\d{02})', '(\d{4})-(\d{2})-(WA\d{02})']
extexif = ['.jpg', '.jpeg', '.png', '.bmp', '.tiff', '.dng']
extraw = ['.rw2', '.cr2']
filetime = ['mp4']
undatedfolder = os.path.join(args.dir, "undated")

# MAIN SCRIPT
for (dirpath, dirnames, filenames) in walk(args.dir):
    n = len(filenames)
    i = 1
    for filename in filenames:
        filepath = os.path.join(args.dir, filename)
        found = False


        ##################
        # PREFIXES       #
        ##################
        for prefix in prefixes:
            if filename.startswith(prefix):
                yearmonth = filename[len(prefix):len(prefix) + 6]

                found = True
                move(args.dir, yearmonth, filename, i, n)
                i = i+1
                break


        ##################
        # REGEXP         #
        ##################
        for regexp in regexps:
            pattern = re.compile(regexp)
            mtch = re.search(pattern, filename)
            if not found and mtch:
                date = mtch.group()
                yearmonth = date[:4] + date[5:7]

                found = True
                move(args.dir, yearmonth, filename, i, n)
                i = i+1
                break


        ############################
        # EXIF with extensions     #
        ############################
        for extension in extexif:
            if not found and filename.lower().endswith(extension.lower()):
                f = open(filepath, 'rb')
                tags = exifread.process_file(f)
                
                datetime = tags['Image DateTime'].values
                yearmonth = datetime[:4] + datetime[5:7]

                found = True
                move(args.dir, yearmonth, filename, i, n)
                i = i + 1 
                break


        ############################
        # RAW with extensions      #
        ############################
        for extension in extraw:
            if not found and filename.lower().endswith(extension.lower()):
                result = subprocess.run(['identify', '-verbose', filepath], stdout=subprocess.PIPE)
                resstr = result.stdout.decode('utf-8')

                for line in resstr.splitlines():
                    if line.strip().startswith('dng:create.date'):
                        l = line.strip()
                       
                        yearmonth = l[17:21] + l[22:24]

                        found = True
                        move(args.dir, yearmonth, filename, i, n)
                        i = i + 1 
                        break
                break


        ############################
        # File time (video)        #
        ############################
        for extension in filetime:
            if not found and filename.lower().endswith(extension.lower()):
                t = time.gmtime(os.path.getmtime(filepath))
                yearmonth = str(t[0]) + str(t[1]).zfill(2)

                found = True
                move(args.dir, yearmonth, filename, i, n)
                i = i + 1 
                break


        ##################
        # DEFAULT        #
        ##################
        if not found:
            # To default folder
            if not os.path.exists(undatedfolder):
                os.makedirs(undatedfolder)

            # Move
            fto = os.path.join(undatedfolder, filename)
            shutil.move(filepath, fto)

            print("%d of %d - %d%% completed: %s" % (i, n, i*100.0/n, filename))
            i = i+1

    break
